name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --verbose
    - name: test
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --verbose
    - name: clippy
      uses: actions-rs/clippy-check@v1.0.7
